name: 💡 Feedback / Feature request
description: Suggest an improvement, a new feature, or share general feedback.
title: "[Feedback]: "
labels: ["feedback"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: What problem would this solve for you?
    validations:
      required: false
